apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: RaspberryPi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: raspberry-pi-chart
    repoURL: https://github.com/rromanotero/test_repo_cd.git
    targetRevision: HEAD
